# Generated by Django 5.2.4 on 2025-07-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Invoice')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('last_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('document_type', 'year', 'month')},
            },
        ),
    ]
