# Generated by Django 5.2.4 on 2025-07-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_numbersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR'), ('CNY', 'CNY'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='PKR', max_length=3),
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR'), ('CNY', 'CNY'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='PKR', max_length=3),
        ),
    ]
