# Generated by Django 5.2.4 on 2025-07-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_options_client_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR'), ('CNY', 'CNY'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='PKR', max_length=10),
        ),
    ]
