# Generated by Django 5.2.4 on 2025-07-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_interaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_type',
            field=models.CharField(choices=[('none', 'No Tax'), ('gst_18', 'GST 18%'), ('gst_17', 'GST 17%'), ('srb_15', 'SRB 15%')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='tax_type',
            field=models.CharField(choices=[('none', 'No Tax'), ('gst_18', 'GST 18%'), ('gst_17', 'GST 17%'), ('srb_15', 'SRB 15%')], default='none', max_length=20),
        ),
    ]
