# Generated by Django 5.2.4 on 2025-07-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_financialaccount_financialactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the quotation scope'),
        ),
    ]
