# Generated by Django 5.2.4 on 2025-07-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_quotation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialactivity',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Cost center or department for expense allocation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialactivity',
            name='expense_category',
            field=models.CharField(blank=True, help_text='Specific expense category for detailed tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialactivity',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice reference for expense tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialactivity',
            name='project_number',
            field=models.CharField(blank=True, help_text='Project reference number for expense tracking', max_length=100, null=True),
        ),
    ]
