# Generated by Django 5.2.4 on 2025-07-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_project_financialactivity_project_invoice_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='estimated_budget',
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Project budget', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(help_text='Project code/number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('construction', 'Construction'), ('service', 'Service'), ('rebuilding', 'Rebuilding'), ('maintenance', 'Maintenance'), ('consulting', 'Consulting'), ('design', 'Design'), ('inspection', 'Inspection'), ('other', 'Other')], default='construction', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20),
        ),
    ]
