# Generated by Django 5.2.4 on 2025-08-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fix_project_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase Order Number', max_length=50, null=True),
        ),
    ]
