# Generated by Django 5.2.4 on 2025-08-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_po_number_to_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='purchase_requisition',
            field=models.CharField(blank=True, help_text='Purchase Requisition Number', max_length=50, null=True),
        ),
    ]
