# Generated by Django 5.2.4 on 2025-08-11 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_quotation_purchase_requisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_predefined', models.BooleanField(default=False, help_text='System predefined category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.projectexpensecategory')),
            ],
            options={
                'verbose_name_plural': 'Project Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('subcategory', models.CharField(blank=True, help_text='Sub-category or specific description', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the expense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR'), ('CNY', 'CNY'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='PKR', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('digital_wallet', 'Digital Wallet'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('expense_date', models.DateField(help_text='Date when the expense was incurred')),
                ('payment_date', models.DateField(blank=True, help_text='Date when payment was made', null=True)),
                ('vendor_name', models.CharField(blank=True, help_text='Vendor or supplier name', max_length=200)),
                ('vendor_contact', models.CharField(blank=True, help_text='Vendor contact information', max_length=100)),
                ('invoice_reference', models.CharField(blank=True, help_text='Vendor invoice number', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks')),
                ('attachment', models.FileField(blank=True, help_text='Receipt, invoice, or supporting document', null=True, upload_to='project_expense_attachments/%Y/%m/')),
                ('attachment_name', models.CharField(blank=True, max_length=200)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate percentage', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Amount including tax', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.project')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.projectexpensecategory')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'expense_date'], name='api_project_project_1e3e07_idx'), models.Index(fields=['category'], name='api_project_categor_bbbae5_idx'), models.Index(fields=['status'], name='api_project_status_ad9fb5_idx'), models.Index(fields=['expense_number'], name='api_project_expense_5c5821_idx')],
            },
        ),
    ]
