services:
  - type: web
    name: bs-engineering-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bs_engineering_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bs_engineering_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

  - type: web
    name: bs-engineering-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: bs-engineering-backend
          type: web
          property: host

databases:
  - name: bs_engineering_db
    databaseName: bs_engineering
    user: bs_engineering
    plan: free
